django_blog/blog/urls.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  2 07:10:15 2020

@author: igor
"""

from django.conf.urls import url
from . import views

urlpatterns = [
        url(r'^',views.home,name='home'),
        url(r'^([0-9]+)/$',views.home,name='home'),
        url(r'^create/',views.create,name='create'),
        url(r'^edit/([0-9]+)/$',views.edit,name='edit'),
        url(r'^delete/([0-9]+)/$',views.delete,name='delete'),
        url(r'^find/',views.find,name='find'),
        url(r'^check/',views.check,name='check'),
        url(r'^message/',views.message,name='message'),
        url(r'^([0-9]+)/$',views.message,name='message'),
    ]

django_blog/django_blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/',include('blog.urls')),
    url(r'^sns/',include('sns.urls')),
]

django_blog/blog/models.py
from django.db import models
from django.core.validators import ValidationError
import re
# Create your models here.

def number(value):
    if(re.match(r'^[0-9]*$',value) == None):
        raise ValidationError('%(value)s is not Number',\
                              params={'value':value},)

class Friend(models.Model):
    name = models.CharField(max_length=100)
    mail = models.EmailField(max_length=200)
    gender = models.BooleanField()
    age = models.IntegerField(default=0)
    birthday = models.DateField()
    
    def __str__(self):
        return '<Friend:id=' + str(self.id) + '  ' + \
            self.name + '(' + str(self.age) + ')>'
            
class Message(models.Model):
    friend = models.ForeignKey(Friend,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=300)
    pub_date = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return '<Message:id='+str(self.id)+','+self.title+'('+str(self.pub_date)+')'
      
    class Meta:
        ordering = ('pub_date',)
    
        

django_blog/blog/forms.py
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Mar  2 11:19:21 2020

@author: igor
"""

from django import forms
from .models import Friend,Message 

class FriendForm(forms.ModelForm):
    class Meta:
        model = Friend
        fields = ['name','mail','gender','age','birthday']
        
class FindForm(forms.Form):
    find = forms.CharField(label='Find',required=False)
    
class CheckForm(forms.Form):
    str = forms.CharField(label='Message')
    
    def clean(self):
        cleaned_data = super().clean()
        str = cleaned_data['str']
        if(str.lower().startswith('no')):
            raise forms.ValidationError('You input NO')
            
class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ['title','content','friend']            
            
            
            
   

django_blog/blog/views.py
from django.shortcuts import render,redirect
from .models import Friend,Message
from .forms import FindForm,CheckForm,FriendForm,MessageForm
from django.db.models import Count,Sum,Avg,Min,Max
from django.core.paginator import Paginator

#from django.db.models import Q

# Create your views here.
def home(request,num=1):
    data = Friend.objects.all()
    pagenator = Paginator(data,3)
    page_object = pagenator.page(num)
    #page_number = request.GET.get('page')
    params = {
            'title':'Hello',
            'message':'',
            'data':page_object,
            }
    return render(request,'blog/blog_home.html',params)

def create(request):
    if(request.method == 'POST'):
        obj = Friend()
        friend = FriendForm(request.POST,instance=obj)
        friend.save()
        return redirect('Http://localhost:8000/blog/home/')
    params = {
            'title':'Hello',
            'form':FriendForm()
            }
    return render(request,'blog/create.html',params)

def edit(request,num):
    obj = Friend.objects.get(id=num)
    if(request.method == 'POST'):
        friend = FriendForm(request.POST,instance=obj)
        friend.save()
        return redirect('http://localhost:8000/blog/home/')
    params = {
            'title':'Hello',
            'id':num,
            'form':FriendForm(instance=obj),
            }
    return render(request,'blog/edit.html',params)

def delete(request,num):
    friend = Friend.objects.get(id=num)
    if(request.method == 'POST'):
        friend.delete()
        return redirect('http://localhost:8000/blog/home/')
    params = {
            'title':'Hello',
            'id':num,
            'obj':friend,
            }
    return render(request,'blog/delete.html',params)

def find(request):
    if(request.method == 'POST'):
        msg = 'search result:'
        form = FindForm(request.POST)
        str = request.POST['find']
        list = str.split()
        data = Friend.objects.all()[int(list[0]):int(list[1])]
    else:
        msg = 'search words...'
        form = FindForm()
        data = Friend.objects.all()
    params = {
            'title':'Hello',
            'message':msg,
            'form':form,
            'data':data,
            }
    return render(request,'blog/find.html',params)

def check(request):
    params = {
            'title':'Hello',
            'message':'check validation.',
            'form':FriendForm(),
            }
    if (request.method == 'POST'):
        obj = Friend()
        form = FriendForm(request.POST,instance=obj)
        params['form'] = form
        if (form.is_valid()):
            params['message'] = 'OK'
        else:
            params['message'] = 'no good.'
    return render(request,'blog/check.html',params)

def message(request,page=1):
    if(request.method == 'POST'):
        obj = Message()
        form = MessageForm(request.POST,instance=obj)
        form.save()
    data = Message.objects.all().reverse()
    paginator = Paginator(data,5)
    page_obj = paginator.page(page)
    params = {
        'title':'Message',
        'form':MessageForm(),
        'data':page_obj,
            }
    return render(request,'blog/message.html',params)

django_blog/blog/templates/blog/blog_home.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charaset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'blog/css/style.css' %}"/>
</head>
<body>
    <h1>{{title}}</h1>
    <p>{{message|safe}}</p>
    <table>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>age</th>
            <th>mail</th>
            <th>birthday</th>
            <th>Messages</tH>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>{{item.age}}</td>
            <td>{{item.mail}}</td>
            <td>{{item.birthday}}</td>
            <td><ul>
            {% for ob in item.message_set.all %}
                <li>{{ob.title}}</li>
            {% endfor %}
            </ul></td>
        </tr>
    {% endfor %}
    </table>
    <div>
        {% if data.has_previous %}
            <a href="{% url 'home' %}">&laquo; first</a>
            <a href="{% url 'home' data.previous_page_number %}">&laquo; prev</a>
        {% endif %}
        <span class="current">
                [{{data.number}}/{{data.paginator.num_pages}}]
        </span>
        {% if data.has_next %}
            <a href="{% url 'home' data.next_page_number %}">next &raquo;</a>
            <a href="{% url 'home' data.paginator.num_pages %}">last &raquo;</a>
        {% endif %}
    </div>
</body>
</html>

django_blog/blog/templates/blog/check.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charaset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'blog/css/style.css' %}"/>
</head>
<body>
    <h1>{{title}}</h1>
    <p>{{message}}</p>
    <hr>
    <oL>
    {% for item in form %}
    <li>{{item.name}} ({{item.value}})
           :{{item.errors.as_text}}</li>
    {% endfor %}
    </oL>
    <table>
        <form action="{% url 'check' %}" method="post">
        {% csrf_token %}
        <tr><th>name</th><td>{{form.name}}</td></tr>
        <tr><th>mail</th><td>{{form.mail}}</td></tr>
        <tr><th>gender</th><td>{{form.gender}}</td></tr>
        <tr><th>age</th><td>{{form.age}}</td></tr>
        <tr><th>birthday</th><td>{{form.birthday}}</td></tr>
        <tr><th></th><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
</body>
</html>

django_blog/blog/templates/blog/create.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charaset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'blog/css/style.css' %}"/>
</head>
<body>
    <h1>{{title}}</h1>
    <table>
        <form action="{% url 'create' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><tD></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
</body>
</html>

django_blog/blog/templates/blog/delete.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charaset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'blog/css/style.css' %}"/>
</head>
<body>
<p>Are you sure to delete this?</p>
    <h1>{{title}}</h1>
    <table>
      <tr><th>ID</th><td>{{obj.id}}</td></tr>
      <tr><th>Name</th><td>{{obj.name}}</td></tr>
      <tr><th>Gender</th><td>
      {% if obj.gender == False %}male{% endif %}
      {% if obj.gender == True %}female{% endif %}
      <tr><th>Email</th><td>{{obj.mail}}</td></tr>
      <tr><th>Age</th><td>{{obj.age}}</td></tr>
      <tr><th>Birth</th><td>{{obj.birthday}}</td></tr>
      <form action="{% url 'delete' id %}" method="post">
      {% csrf_token %}
      <tr><th></th><td><input type="submit" value="click"></td></tr>
      </form>
    </table>
</body>
</html>

django_blog/blog/templates/blog/edit.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charaset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'blog/css/style.css' %}"/>
</head>
<body>
    <h1>{{title}}</h1>
    <table>
        <form action="{% url 'edit' id %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><tD></td><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
</body>
</html>

django_blog/blog/templates/blog/find.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charaset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'blog/css/style.css' %}"/>
</head>
<body>
    <h1>{{title}}</h1>
    <p>{{message|safe}}</p>
    <table>
        <form action="{% url 'find' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <tr><th></th><td><input type="submit" value="click"></td></tr>
        </form>
    </table>
    <hr>
    <table>
        <tr>
            <th>id</th>
            <th>name</th>
            <th>age</th>
            <th>mail</th>
            <th>birthday</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.id}}</td>
            <td>{{item.name}}</td>
            <td>{{item.age}}</td>
            <td>{{item.mail}}</td>
            <td>{{item.birthday}}</td>
        </tr>
    {% endfor %}
    </table>
</body>
</html>

django_blog/blog/templates/blog/message.html
{% load static %}
<!doctype html>
<html lang="ja">
<head>
    <meta charaset="utf-8">
    <title>{{title}}</title>
    <link rel="stylesheet" type="text/css"
        href="{% static 'blog/css/style.css' %}"/>
</head>
<body>
    <h1>{{title}}</h1>
    <table>
        <form action="{% url 'message' %}" method="post">
        {% csrf_token %}
        {{ form.as_table }}
        <tr><td></td><td><input type="submit" value="send"></td></tr>
        </form>
    </table>
    <hr>
    <table>
        <tr>
            <th>title</th>
            <th>name</th>
            <th>datetime</th>
        </tr>
    {% for item in data %}
        <tr>
            <td>{{item.title}}</td>
            <td>{{item.friend.name}}</td>
            <td>{{item.pub_date}}</td>
        </tr>
    {% endfor %}
    </table>
    <div>
        {% if data.has_previous %}
            <a href="{% url 'message' data.previous_page_number %}">&laquo; prev</a>
        {% endif %}
        {% if data.has_next %}
            <a href="{% url 'message' data.next_page_number %}">next &raquo;</a>
        {% endif %}
    </div>
</body>
</html>